# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bankingmicroservice:
    image: bankingmicroservice
    build:
      context: .
      dockerfile: BankingMicroservice/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5062:5062
      - 7048:7048
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
