@WebApplication1_HostAddress = http://localhost:5062

GET {{WebApplication1_HostAddress}}/allowedactions/User1/Card11
Accept: application/json

###

@WebApplication1_HostAddress = https://localhost:7048

GET {{WebApplication1_HostAddress}}/allowedactions/User1/Card11
Accept: application/json

###

@WebApplication1_HostAddress = http://localhost:32771

GET {{WebApplication1_HostAddress}}/allowedactions/User1/Card11
Accept: application/json

###